### ISSUE TITLE
Auto-join rooms/spaces via SSO attribute mapping

### ISSUE THREAD

**Issue by matrixbot** [element-hq/synapse#10791]
This issue has been migrated from [#10791](https://github.com/matrix-org/synapse/issues/10791).

---

**Description:**

It doesn't seem like this is currently possible? Would be great if I could map SSO attributes to rooms/spaces for new users to be automatically added into. Also would be nice if room/space-level roles could be set.

**Comment by Smoolak** [comment]
I really hope this gets implemented some day. +1

**Comment by ajl199** [comment]
The ideal from my perspective would be if a role:room/space mapping could be created, and that would at least add users to rooms or spaces. Better still if it removed them from those they were no longer entitled to, as well.

Use case: a membership organisation with numerous volunteers and committees, roles are governed centrally through SSO. When, for instance, members of our board change at the AGM, they get the Board role; new board members should find they've gained access to governance related rooms, and ex-board members should lose it.

I'm quite new to synapse, but think the config might look something like:

```
user_mapping_provider:    
  roles_template: "{{ rolesclaim.pertinentroles }}"    
  role_access_map:    
      mapped_rooms:    
        governance:    
          - role1    
          - role2    
        events:    
          - role1    
          - role3    
      mapped_spaces:   
        board:    
          - role1           
        techteam:    
          - role4    
```

Any room/space not listed would be ignored (no access granted or denied), but for those which appear under mapped_rooms and mapped_spaces, if the user had one of the listed roles and was not in, they'd get added, and if they were in, but didn't have the role they'd be removed.
