### ISSUE TITLE
Server Notices – room_avatar

### ISSUE THREAD

**Issue by matrixbot** [element-hq/synapse#12831]
This issue has been migrated from [#12831](https://github.com/matrix-org/synapse/issues/12831).

---

Hey

I just set up `server_notices` and found that the room avatar would be a better option than `system_mxid_avatar_url` or just having both.

Or is it already available but not [documented](https://github.com/matrix-org/synapse/blob/develop/docs/server_notices.md)?

Something like this:
```
server_notices:
   system_mxid_localpart: server
   system_mxid_display_name: "Server Notices"
   system_mxid_avatar_url: "mxc://server.com/oumMVlgDnLYFaPVkExemNVVZ"
   room_name: "Server Notices"
   room_avatar: "mxc://server.com/oumMVlgDnLYFaPVkExemNVVZ"
```

Thanks!
