### ISSUE TITLE
Add Redis Sentinel support

### ISSUE THREAD

**Issue by matrixbot** [element-hq/synapse#15122]
This issue has been migrated from [#15122](https://github.com/matrix-org/synapse/pull/15122).

---

I would like to add support for [Redis Sentinel](https://redis.io/docs/management/sentinel/) to support high availabilty redis, which this PR hopefully fixes. It's not perfect, but it's a start.

1. I've tried to create a bit of an abstraction layer so we could remove the import of the `txredisapi` from the different parts of the code.
2. I added a redis factory which initializes the redis connection and the replication factory based on the redis configuration.
3. The 'regular' redis connection is still the same (though in a different place) and will still be used as the default.
4. Automated testing I'm not sure about, so any help in that area would be appreciated.

For local testing I've use the following docker compose file

```
version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=testing
    networks:
      - app-tier
    ports:
      - '6379:6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_PASSWORD=testing
      - REDIS_MASTER_PASSWORD=testing
    ports:
      - '6379'
    depends_on:
      - redis
    networks:
      - app-tier
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=testing
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379-26381:26379'
    networks:
      - app-tier
```

And running it as follows to start 3 sentinels:

`docker-compose up --scale redis-sentinel=3 -d redis-sentinel`

The config can then be set to:
```
redis:
  enabled: True
  sentinel: true
  sentinels:
    - host: localhost
      port: 26380
    - host: localhost
      port: 26379
    - host: localhost
      port: 26381
  dbid: <<<Database Name>>>
  password: 'testing'
```

Let me know what you guys think, I'm sure there's some improvements to be made.

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Roel ter Maat [9532678+roeltm@users.noreply.github.com](mailto:9532678+roeltm@users.noreply.github.com)
