### ISSUE TITLE
Background jobs for `notify_interested_services_ephemeral` appear to stack up with MSC3202+MSC2409 enabled

### ISSUE THREAD

**Issue by matrixbot** [element-hq/synapse#15363]
This issue has been migrated from [#15363](https://github.com/matrix-org/synapse/issues/15363).

---

### Description

![image](https://user-images.githubusercontent.com/1190097/229266356-066dacaf-4d3b-43bb-86e4-0ce78f8e7aca.png)

^ This doesn't seem great. The cliff towards the end is a restart, where naturally the jobs clear themselves out.

### Steps to reproduce

1. Run MSC3202-compatible appservice

### Homeserver

t2bot.io

### Synapse Version

{"server_version":"1.80.0","python_version":"3.8.10"}

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL

### Workers

Multiple workers

### Platform

Ubuntu machine. Contact for specifics.

### Configuration

```yaml
experimental_features:
  msc2409_to_device_messages_enabled: true
  msc3202_device_masquerading: true
  msc3202_transaction_extensions: true
```

then in the appservice config (there's only one such appservice):

```yaml
id: rss
hs_token: redacted
as_token: redacted
namespaces:
  users: []
  aliases: []
  rooms: []
url: 'redacted'
sender_localpart: rss
rate_limited: false
protocols: null
de.sorunome.msc2409.push_ephemeral: true
org.matrix.msc3202: true
```

### Relevant log output

```shell
N/A
```

### Anything else that would be useful to know?

The appservice on the receiving side has encryption enabled, so will be receiving such traffic. t2bot.io also runs with presence enabled (on a dedicated worker). Typing notifications are on a dedicated worker as well.

t2bot.io also runs a custom patch in this area: https://github.com/t2bot/synapse/commit/f197757b883cb234e57fb2aff8192255ff6c41ce
