### ISSUE TITLE
rc_joins rate limits dont function

### ISSUE THREAD

**Issue by matrixbot** [element-hq/synapse#16002]
This issue has been migrated from [#16002](https://github.com/matrix-org/synapse/issues/16002).

---

### Description

For test purposes i added this to my homeserver yaml: 
```

rc_joins:
  local:
    per_second: 1000
    burst_count: 2000
  remote:
    per_second: 1000
    burst_count: 2000
```

but i still can just join 10 rooms and then get the rate limit error

### Steps to reproduce

change config and try to join a bunch of rooms at once

### Homeserver

my own

### Synapse Version

1.88.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

Postgres 15

### Workers

Single process

### Platform

Docker

### Configuration

see discription 

### Relevant log output

```shell
MatrixError: [429] Too Many Requests
```
