### ISSUE TITLE
`user_mapping_provider` support in `jwt_config`

### ISSUE THREAD

**Issue by col-panic** [element-hq/synapse#17807]
**Description:**

`oidc_providers` do support the inital mapping of values on user creation via
```
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.name }}"
        email_template: "{{ user.email }}"
```

Could this be equally provided for `jwt_config`? Here the only value
available seems to be `subject_claim`. 

I'm currently working on updating the Java Client to Server library and I found this when working on https://github.com/col-panic/Matrix-ClientServer-API-java/blob/98ef8dc6392306f41757ac14600606fef4160ac8/src/main/java/de/jojii/matrixclientserver/Bot/Client.java#L104

Current config is
```
jwt_config:
    enabled: true
    issuer: "https://${EE_HOSTNAME}/keycloak/auth/realms/ElexisEnvironment"
    algorithm: RS256
    secret: |
      -----BEGIN PUBLIC KEY-----
      ${REALM_PUBLIC_KEY}
      -----END PUBLIC KEY-----
    subject_claim: "preferred_username"
    audiences:
        - "synapse"
 ```
