### ISSUE TITLE
Messages retention is not deleting messages older than 30 days

### ISSUE THREAD

**Issue by Gushtera** [element-hq/synapse#17925]
Hello Guys,

For some reason the retention is not working for messages older than 30 days. Basically, it's not deleting any messages. Can someone help what can be the reason? Here is the configuration:

```yaml
retention:
  enabled: true
  default_policy:
    min_lifetime: "1d"
    max_lifetime: "30d"
  purge_jobs:
    - type: "messages"
      interval: "1d"
```
