### ISSUE TITLE
Can't get SSO to match authentik user to existing user

### ISSUE THREAD

**Issue by sakibstark11** [element-hq/synapse#18008]
I've been using matrix for about a year now. Recently I started switching my services over to `authentik` and I did the same for matrix synapse. Except an issue I seem to be getting is despite both matrix and authentik sharing the same user name, when I log in with authentik, it creates a new user. I am not sure if this is a bug or not.
I'll add some of my configs here for clarity.
```
...yml
enable_registration: false
oidc_providers:
    - idp_id: authentik
      idp_name: authentik
      allow_existing_users: true
      discover: true
      issuer: "https://authentik.me/application/o/matrix/"
      client_id: "secret"
      client_secret: "secret"
      scopes:
          - "openid"
          - "profile"
          - "email"
      user_mapping_provider:
          config:
              localpart_template: "{{ user.preferred_username }}"
              display_name_template: "{{ user.name }}"
              email_template: "{{ user.email }}"
```
Any assistance would be much appreciated. Thanks

**Comment by sakibstark11** [comment]
Strange that I'm not getting any comments. Perhaps I've not given enough information. Feel free to let me know what else I need to add.

**Comment by sakibstark11** [comment]
So i had to remove the existing bindings (api calls to set external_ids: []), and using 
```yaml
      allow_existing_users: true
      enable_registration: false
      user_mapping_provider:
          config:
              localpart_template: "{{ user.preferred_username }}"
              display_name_template: "{{ user.name }}"
              email_template: "{{ user.email }}"
```
worked,
