### ISSUE TITLE
New parameter for `media_retention`: `spare_local_media_below_filesize`

### ISSUE THREAD

**Issue by composite9239** [element-hq/synapse#18199]
**Description:**

Allows users to spare media below a certain filesize, in bytes. This seems like it would be straightforward to implement and helpful for people who only want large media files to be deleted automatically.

In the same vein, `spare_remote_media_below_filesize` might as well also be added (0 by default, of course).

Example config:

```
media_retention:
    local_media_lifetime: 90d
    spare_local_media_below_filesize: 10000000
    remote_media_lifetime: 14d
    spare_remote_media_below_filesize: 0
```
