### ISSUE TITLE
Workers don't support POST requests to MSC4140 delayed_events endpoints

### ISSUE THREAD

**Issue by Dual-0** [element-hq/synapse#18328]
Workers don't support POST requests to MSC4140 delayed_events endpoints

## Description

While implementing Element Call/Matrix RTC support as documented in https://github.com/element-hq/element-call/blob/main/docs/self-hosting.md, I encountered an issue with MSC4140 delayed events when using workers.

The current worker documentation includes:

```
Additionally, the following REST endpoints can be handled for GET requests:
    ^/_matrix/client/(api/v1|r0|v3|unstable)/pushrules/
    ^/_matrix/client/unstable/org.matrix.msc4140/delayed_events
```

However, in practice, the worker returns 404 responses when handling POST requests to these endpoints.

## Steps to Reproduce

1. Set up a Synapse server with workers following the worker documentation
2. Configure the required MSCs for Element Call as per documentation:
   ```yaml
   experimental_features:
     msc3266_enabled: true
     msc4222_enabled: true
     msc4140_enabled: true
   
   max_event_delay_duration: 24h
   
   rc_delayed_event_mgmt:
     per_second: 1
     burst_count: 20
   ```
3. Configure a status_persister worker with `experimental_features: msc4140_enabled: true`
4. Route MSC4140 endpoints to the worker
5. Observe 404 errors when Element Call tries to make POST requests to delayed_events endpoints

## Error Messages
```
SynapseError: 404 - Unrecognized request
POST /_matrix/client/unstable/org.matrix.msc4140/delayed_events/syd_*
```

## Solution
Routing MSC4140 requests to the main process instead of a worker resolves the issue:

```nginx
location ~ ^/_matrix/client/unstable/org\.matrix\.msc4140/delayed_events {
    proxy_pass http://main_process;
    # Other proxy settings...
}
```

## Additional Information
The documentation currently lists `^/_matrix/client/unstable/org.matrix.msc4140/delayed_events` as an endpoint workers can handle, but only mentions it's for GET requests. This is easy to miss, as Element Call primarily uses POST requests for heartbeats and delayed event management.
