### ISSUE TITLE
Ability to disable End-To-End Encryption via Config

### ISSUE THREAD

**Issue by matrixbot** [element-hq/synapse#4401]
This issue has been migrated from [#4401](https://github.com/matrix-org/synapse/issues/4401).

---

**Description:**
Originally proposed in vector-im/element-web#4367  - for the case of vector-im/element-web#4367 is was sufficient to address  via power level settings. Creating a new issue to track doing this via a config setting. 

The original ask:-
"I would like the ability to disable end-to-end encryption in my self hosted Synapse instance. I have a legal requirement to provide audit-able chat logs, which is obviously impossible if there's nothing preventing my end-users from encrypting any room they create."

**Comment by amsnek** [comment]
I would want to know as well. For my Setup/Envionment, we would require the ability to disable E2EE (or have means to provide users their encrypted Keys on request after them losing it, not storing the receovery key etc.).

**Comment by mhtvsSFrpHdE** [comment]
Resumed from here (repository was archived): https://github.com/matrix-org/synapse/issues/4401#issuecomment-1637200850

@grantm I owe you my thanks, user registered on my home server finally no longer have to worry about accidentally enable encryption and risk in lost access to chat history in future anymore

If one want E2EE, can definelly register and chat on official matrix server, or host his own

For those who also want to know how to config this  
Assume Debian, `sudo nano /etc/matrix-synapse/homeserver.yaml`  
First part: add a well known announcement, disabling encryption by default  
From https://github.com/element-hq/element-web/blob/develop/docs/e2ee.md
```
serve_server_wellknown: true
public_baseurl: "https://<your server domain>/"
extra_well_known_client_content:
  io.element.e2ee:
    default: false
    force_disable: true
```
Second part: override permission, from https://github.com/matrix-org/synapse/issues/4401#issuecomment-1637200850
```
encryption_enabled_by_default_for_room_type: off
default_power_level_content_override:
  private_chat:
    "events":
      "m.room.avatar": 50
      "m.room.canonical_alias": 50
      "m.room.encryption": 999
      "m.room.history_visibility": 100
      "m.room.name": 50
      "m.room.power_levels": 100
      "m.room.server_acl": 100
      "m.room.tombstone": 100
    "events_default": 0
  trusted_private_chat:
    "events":
      "m.room.avatar": 50
      "m.room.canonical_alias": 50
      "m.room.encryption": 999
      "m.room.history_visibility": 100
      "m.room.name": 50
      "m.room.power_levels": 100
      "m.room.server_acl": 100
      "m.room.tombstone": 100
    "events_default": 0
  public_chat:
    "events":
      "m.room.avatar": 50
      "m.room.canonical_alias": 50
      "m.room.encryption": 999
      "m.room.history_visibility": 100
      "m.room.name": 50
      "m.room.power_levels": 100
      "m.room.server_acl": 100
      "m.room.tombstone": 100
    "events_default": 0
```
Stop and start server, from now on newly created direct chat or ordinary room can't be encrypted, exist room created before are not affected by this and still possible to be encrypted
